language: python
python:
  - "3.7"
install:
  - pip install coveralls
  - pip install -r requirements-test.txt
script:
  - pytest
after_success:
  - pytest --cov
  - coveralls
notifications:
  slack: cyborged:37K3wQ7qoWjZ1FM2cf7TdJTC