language: python
python:
- '3.7'
install:
- pip install coveralls
- pip install -r requirements-test.txt
script:
- pytest
after_success:
- pytest --cov
- coveralls
notifications:
  slack:
    rooms:
      secure: JFhJ7DeRRnNT9eNf83kZD189VkaArk9Sv0/hhEVrCSaEmpw6iL7hSpQxLjMshAxnTmWxefIdaCvdiDyrrUF9mXVkEIjt4eBIlXXhlx1I+qJpozSkq3xD9Le+YWkl5BkUMtKbq+H7d39Tgu6ORjpVrO7aQTht+ShVlcNHFkzwiejFsyrCPRS2JFBMsbIpQiNchGfReHXjqhSfijK9VxGSp1Brjab2V4cPPKsvm03mYw7Yibm9UNM6uQSpv6nfAahWCxp5BCcxXpecgkVstTqbh2Ec09d7I7NqGPt8yw0XTks7h9HtheP51QeoktrZ4atlko3pkSSNWT3NDxL12nx1PA3nKs3+r9ieNR01MktpVeTjwuX+NGUDDYBmGsb34wvM3hJqrEalyH4nx4CDosyvYeJXjOEFclla8XweHR88jIFA6/UPH6DNxsojmMKW8Xttis+QI37B2xm0p5SJDae/4xzc+fzpKgQY/xpya5sEoVhfi1lij2k+ppILTKpnLzFSvPyubeOgSYDfGM58ngo++P/TBFwheT557jZGcLgBdal1gZKCPzx994brMiYGl0FdnklIv7/z6KCtqstlM3rMfSo4vzFxQNSIfwjgJ7/yZ/j2nkeQV76Xl+IsCWQL08j+JR1bYhzIpGBMqt0S+jBAd1l7da5pM/PK4LPst+htPpQ=
