# Generated by Django 3.0.4 on 2020-03-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_question", models.CharField(max_length=1000)),
                ("fact_answer", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="Myths",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myth_question", models.CharField(max_length=1000)),
                ("myth_answer", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="Prevention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prevention_question", models.CharField(max_length=1000)),
                ("prevention_answer", models.CharField(max_length=10000)),
            ],
        ),
    ]
