# Generated by Django 3.0.4 on 2020-03-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("covid19_sections", "0001_initial")]

    operations = [
        migrations.RenameModel(old_name="Facts", new_name="Fact"),
        migrations.RenameModel(old_name="Myths", new_name="Myth"),
    ]
