# Generated by Django 3.0.4 on 2020-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("covid19_sections", "0002_auto_20200311_1206")]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="fact_answer",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="myth",
            name="myth_answer",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="prevention",
            name="prevention_answer",
            field=models.TextField(max_length=10000),
        ),
    ]
