# Generated by Django 3.0.4 on 2020-03-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("covid19_sections", "0003_auto_20200311_1207")]

    operations = [
        migrations.RenameField(
            model_name="fact", old_name="fact_answer", new_name="answer"
        ),
        migrations.RenameField(
            model_name="fact", old_name="fact_question", new_name="question"
        ),
        migrations.RenameField(
            model_name="myth", old_name="myth_answer", new_name="answer"
        ),
        migrations.RenameField(
            model_name="myth", old_name="myth_question", new_name="question"
        ),
        migrations.RenameField(
            model_name="prevention",
            old_name="prevention_answer",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="prevention",
            old_name="prevention_question",
            new_name="question",
        ),
    ]
