# Generated by Django 3.0.4 on 2020-03-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("covid19_sections", "0005_helplines")]

    operations = [
        migrations.RenameModel(old_name="Helplines", new_name="Helpline")
    ]
