# Generated by Django 3.0.4 on 2020-03-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("covid19_sections", "0007_auto_20200317_1513")]

    operations = [
        migrations.AlterField(
            model_name="helpline",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="covid19_sections.Country",
            ),
        )
    ]
