# Generated by Django 3.0.4 on 2020-03-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("covid19_sections", "0008_auto_20200317_1513")]

    operations = [
        migrations.AddField(
            model_name="country",
            name="information_source",
            field=models.CharField(blank=True, max_length=50),
        )
    ]
